#!/bin/sh
# setup-docs.sh — idempotent content symlinker for the Mintlify docs site.
# Generated by doc-site (renderer: mintlify/both; contentMode: symlink|mixed). Do not
# edit by hand; re-running the generator regenerates this file (a hand edit is detected
# and the file is skipped — see .doc-site-scaffold.json provenance).
#
# Creates RELATIVE-path symlinks from the Mintlify content root (the project directory
# that holds docs.json) to the repo-root markdown that is the single source of truth.
# Idempotent: re-running yields the same links (ln -sf / ln -sfn) and a no-op git diff.
set -eu

# --- Resolve repo root and the Mintlify content directory --------------------
# The script lives at docs/setup-docs.sh, so repo root is computed
# relative to the script's own location (works regardless of caller CWD). Unlike the
# Starlight variant, the content root IS the project directory (docs.json lives here) —
# there is no src/content/docs collection and no Astro cache to clear.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
DOCS_PKG_DIR="$REPO_ROOT/docs"
CONTENT_DIR="$DOCS_PKG_DIR"

echo "Setting up documentation symlinks..."
echo "  Repo root:   $REPO_ROOT"
echo "  Content dir: $CONTENT_DIR"

mkdir -p "$CONTENT_DIR"

# --- Safety: refuse any source path that escapes the repo tree (REQ-SEC-02) --
# Canonicalize the resolved target and assert it is inside $REPO_ROOT before
# linking. See 08-rerun-and-verification.md for the authoritative policy.
assert_inside_repo() {
  # $1 = repo-relative source path (the manifest `from` value, or images dir)
  _src="$REPO_ROOT/$1"
  _dir=$(dirname "$_src")
  if [ ! -d "$_dir" ]; then
    echo "ERROR: source directory does not exist: $_dir" >&2
    exit 1
  fi
  # Canonicalize the directory (follows .. and symlinks) then re-append basename.
  _canon_dir=$(cd "$_dir" && pwd -P)
  _canon="$_canon_dir/$(basename "$_src")"
  _root_canon=$(cd "$REPO_ROOT" && pwd -P)
  case "$_canon" in
    "$_root_canon"/*) : ;;  # inside repo — ok
    *)
      echo "ERROR: refusing symlink target outside repo root: $1" >&2
      echo "       resolved to: $_canon (repo root: $_root_canon)" >&2
      exit 1
      ;;
  esac
}

# --- rel_path: pure-POSIX relative path from $1 (dir) to $2 (file/dir) --------
# Both args are absolute. Emits a path relative to $1 that resolves to $2, using
# only canonicalized absolute prefixes (no realpath --relative-to, which is GNU).
rel_path() {
  _from=$(cd "$1" && pwd -P)
  _to_dir=$(cd "$(dirname "$2")" && pwd -P)
  _to="$_to_dir/$(basename "$2")"
  _common="$_from"
  _up=""
  while [ "${_to#"$_common"/}" = "$_to" ] && [ "$_common" != "/" ]; do
    _common=$(dirname "$_common")
    _up="../$_up"
  done
  if [ "$_common" = "/" ]; then
    _rest="${_to#/}"
  else
    _rest="${_to#"$_common"/}"
  fi
  printf '%s%s\n' "$_up" "$_rest"
}

# --- link_file: relative-path symlink for a single source=symlink page -------
# $1 = repo-relative source markdown (manifest `from`); $2 = slug (dest name).
# Mintlify resolves an extensionless nav path (guides/setup) to guides/setup.md.
link_file() {
  assert_inside_repo "$1"
  if [ ! -f "$REPO_ROOT/$1" ]; then
    echo "ERROR: symlink source file not found: $1" >&2
    echo "       (nav page '$2' references a missing 'from' target)" >&2
    exit 1
  fi
  _dest="$CONTENT_DIR/$2.md"
  mkdir -p "$(dirname "$_dest")"
  # Guard against source == destination. For Mintlify the content dir IS the project
  # root, so a `from` that already lives at this slug (e.g. from=docs/setup.md with the
  # docs pkg dir itself) would make `ln -sf` overwrite the source with a self-referential
  # symlink and DESTROY the content. Canonicalize both and skip when they coincide — the
  # page body is already in place, no link needed. (Starlight can't hit this: its content
  # dir is src/content/docs/, never the source.)
  _src_canon="$(cd "$(dirname "$REPO_ROOT/$1")" && pwd -P)/$(basename "$1")"
  _dest_canon="$(cd "$(dirname "$_dest")" && pwd -P)/$(basename "$_dest")"
  if [ "$_src_canon" = "$_dest_canon" ]; then
    echo "  skip $2.md — source already at destination (no link needed)"
    return 0
  fi
  # Relative path FROM the destination's directory TO the source file.
  _rel=$(rel_path "$(dirname "$_dest")" "$REPO_ROOT/$1")
  ln -sf "$_rel" "$_dest"
  echo "  linked $2.md -> $_rel"
}

# --- link_dir: --no-dereference dir symlink (images/) -------------------------
# $1 = repo-relative source dir; $2 = dest name under content dir.
# CRITICAL: use ln -sfn (-n = --no-dereference). Without -n, a second run sees an
# existing symlink that points at a directory, dereferences it, and creates the
# new link *inside* the target dir (e.g. images/images), corrupting the tree.
link_dir() {
  assert_inside_repo "$1"
  if [ ! -d "$REPO_ROOT/$1" ]; then
    echo "ERROR: symlink source directory not found: $1" >&2
    exit 1
  fi
  _dest="$CONTENT_DIR/$2"
  # Same source == destination guard as link_file: when the images source already IS the
  # content-root images dir, `ln -sfn` would create a dangling images/images loop inside it.
  _src_canon=$(cd "$REPO_ROOT/$1" && pwd -P)
  if [ -d "$_dest" ] && [ "$(cd "$_dest" 2>/dev/null && pwd -P)" = "$_src_canon" ]; then
    echo "  skip $2/ — source already at destination (no link needed)"
    return 0
  fi
  _rel=$(rel_path "$(dirname "$_dest")" "$REPO_ROOT/$1")
  ln -sfn "$_rel" "$_dest"
  echo "  linked $2/ -> $_rel (no-dereference)"
}

# >>> manifest-managed symlinks (generated from the nav/plan at emit time)
# One link_file call per `source: "symlink"` page; native/unmanaged pages omitted.
link_file "docs-src/getting-started.md" "getting-started"
link_file "docs-src/guides/usage.md" "guides/usage"
# Directory symlink for images so `/images/<x>.png` resolves in Mintlify:
link_dir "docs-src/images" "images"
# <<< manifest-managed symlinks

echo "Done."
